
- hosts: sys1
  become: yes
  vars:
      name: play.data2viz.io

  tasks:

    - name: Deploy git sources from github project {{ name }}
      git:
        repo: git@github.com:data2viz/{{ name }}.git
        dest: /home/d2v/{{ name }}
        accept_hostkey: yes
        force: yes

    - name: build {{ name }}
      command: chdir=/home/d2v/{{ name }}
        ./build.sh

    - name: stop {{ name }}
      ignore_errors: yes
      command: chdir=/home/d2v/{{ name }}
        ./stop.sh

    - name: start {{ name }}
      command: chdir=/home/d2v/{{ name }}
        ./start.sh
